[build]
  command = "ng build --configuration production"
  publish = "fixsell-adminpanel/dist/fixsell-adminpanel-front"
  base = "/"

  [build.budgets]
    [build.budgets.CSS]
      maximumBudget = 12

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
