[build]
  command = "ng build --configuration production"
  publish = "/dist/fixsell-adminpanel-front"

  [build.budgets]
    [build.budgets.CSS]
      maximumBudget = 12

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
